on:
  push:
    branches: [test_branch]

jobs:
  check_site_health:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://example.com|http://example.com
