name: Hello World

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v1
        with: node-version: '12.x'
      - name: Say hello
        run: echo "Hello World!"
      - name: Now it is
        run: date
      - name: Run ls -l
        run: ls -l
      - name: Print commit message if it includes #skip
        if: ${{ contains(toJson(github.event.commits.*.message, '#skip')) }}
        echo: ${{ toJson(github.event.commits.*.message) }}
